### ISSUE TITLE
What is the correct json format for input data?

### ISSUE THREAD

**Issue by vitthal-bhandari** [davidjurgens/potato#41]
Referring to the example given [here](https://github.com/davidjurgens/potato/blob/master/project-hub/simple_examples/data/toy-example.json), I gave the below JSON doc as input data.

```
{
    "IDENTITY_ATTACK": 0.6113662,
    "INSULT": 0.34384298,
    "PROFANITY": 0.4119253,
    "SEVERE_TOXICITY": 0.32176828,
    "THREAT": 0.11071971,
    "TOXICITY": 0.056931525,
    "category": "1",
    "id": 1288,
    "text": "#proudout wishes all a happy New year! #NYE2016 #LGBTQ #LGBT #lesbian #gay #bisexual #transgender #LoveWins #HappyNewYear #gaynewyear"
}
{
    "IDENTITY_ATTACK": 0.013542902,
    "INSULT": 0.0137602305,
    "PROFANITY": 0.005872097,
    "SEVERE_TOXICITY": 0.006128401,
    "THREAT": 0.0034086322,
    "TOXICITY": 0.00057268236,
    "category": "1",
    "id": 8363,
    "text": "Special skills include: telling if someone is gay solely based on that tiny thumbnail that comes up in Gmail."
}
{
    "IDENTITY_ATTACK": 0.84763545,
    "INSULT": 0.68785954,
    "PROFANITY": 0.6092933,
    "SEVERE_TOXICITY": 0.50534093,
    "THREAT": 0.17621756,
    "TOXICITY": 0.0026031018,
    "category": "1",
    "id": 9026,
    "text": "gay for fifth harmony \u30c4"
}
```

I encounter the error below when starting the service.

```
D:\potato>potato start sentiment_analysis
starting server from sentiment_analysis\configs\sentiment-analysis.yaml
the current working directory is: D:\potato\sentiment_analysis
Loading users fromuser_config.json
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\potato.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\potato\cli.py", line 6, in potato
    main()
  File "c:\python38\lib\site-packages\potato\flask_server.py", line 2587, in main
    run_server(args)
  File "c:\python38\lib\site-packages\potato\flask_server.py", line 2558, in run_server
    load_all_data(config)
  File "c:\python38\lib\site-packages\potato\flask_server.py", line 576, in load_all_data
    item = json.loads(line)
  File "c:\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

**Comment by Jiaxin-Pei** [comment]
Hi @vitthal-bhandari, you might need to pack each dict in one line. You could also try to use .csv file which might be easier ([example](https://github.com/davidjurgens/potato/blob/master/project-hub/simple_examples/data/toy-example.csv) for the .csv file)
