### ISSUE TITLE
New data file for existing examples do not work

### ISSUE THREAD

**Issue by fateme-hshm96** [davidjurgens/potato#77]
Hello. Thanks a lot for this nice tool!

I'm having trouble running existing potatoes with my own data. I tried Offensiveness/Politeness which are similar and just changed the yaml file to point to my csv file. Although the log prints my filename, it still shows samples from the previous data file, and since my data file contains fewer samples, I keep getting a KeyError.

My csv header is:
predicted_label,button_color,confidence_score,nda_file_name,text,id

I'm using Python 3.10.12 and I have potato-annotation  1.2.1.5.

Change in the yaml file to use my csv file:
```
"data_files": [
      # "data_files/politeness_rating_3718.csv"
      "data_files/contdata.csv"
    ],
```

Terminal output:
```
potato --verbose --debug start politeness_rating/
multiple config files found, please select the one you want to use (number 0-2)
[0] politeness_2.yaml
[1] politeness.yaml
number: 1
starting server from politeness_rating/configs/politeness.yaml
the current working directory is: politeness_rating/
INFO:potato.flask_server:html_layout will be loaded from user-defined file templates/layout.html
DEBUG:potato.flask_server:Loading data from 1 files
DEBUG:potato.flask_server:Reading data from data_files/contdata.csv
DEBUG:potato.flask_server:Loaded 210 instances from data_files/contdata.csv
DEBUG:potato.flask_server:Found known user "debug_user"; loading annotation state
INFO:potato.flask_server:Loaded 1 annotations for known user "debug_user"
DEBUG:potato.flask_server:Found known user "3"; loading annotation state
INFO:potato.flask_server:Loaded 3 annotations for known user "3"
running at:
localhost:9001
 * Serving Flask app 'potato.flask_server'
 * Debug mode: off
debug user logging in
DEBUG:potato.flask_server:Found known user "debug_user"; loading annotation state
INFO:potato.flask_server:Loaded 1 annotations for known user "debug_user"
ERROR:potato.flask_server:Exception on /annotate [POST]
Traceback (most recent call last):
  File "python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "python3.10/site-packages/potato/flask_server.py", line 1992, in annotate_page
    save_user_state(username)
  File "python3.10/site-packages/potato/flask_server.py", line 1660, in save_user_state
    "displayed_text": instance_id_to_data[inst_id]["displayed_text"],
KeyError: '1953'```

![Screenshot from 2024-02-02 17-21-16](https://github.com/davidjurgens/potato/assets/12449653/05701c12-d1c7-4d08-a4f5-6dc4fafafbe3)

**Comment by Jiaxin-Pei** [comment]
Hey @fateme-hshm96, could you try to remove the annotation_output dir and try again?

**Comment by fateme-hshm96** [comment]
Thanks for your quick response! That solved the issue!

**Comment by Jiaxin-Pei** [comment]
Great!!
