### ISSUE TITLE
1.2.2.1 broke potato annotation tasks

### ISSUE THREAD

**Issue by christianschuler8989** [davidjurgens/potato#81]
Halli und Hallo and Greetings,
I am a big fan of Potato, thank you for creating it! :)
Sadly, I just noticed that something inside of potato must have broken recently.

**Reproduction**
( This error happens either way, whether I install potato-annotation via pip, or clone the repository. )
- I run the command to start the annotation task 
- `potato start summarization_evaluation/`
- The server starts and I can navigate to it via the web browser (Firefox)
- I can create a new account as usual
- The moment I try to log into the annotation task, the browser displays a message along the lines of: "an internal server error has occurred" 

**Error Description / Terminal Output**
```
potato start summarization_evaluation/
starting server from summarization_evaluation/configs/summ-eval.yaml
the current working directory is: /home/username/directory_to_project/summarization_evaluation/
WARNING:potato.flask_server:surveyflow_html_layout not configured, use default template at /home/username/directory_to_project/venvPotato/lib/python3.10/site-packages/potato/base_html/examples/plain_layout.html
running at:
localhost:9001
 * Serving Flask app 'potato.flask_server'
 * Debug mode: off
unknown action at home page
test@test Success
user info file saved at: user_config.json
test@test login successful
ERROR:potato.flask_server:Exception on /login [POST]
Traceback (most recent call last):
  File "/home/username/directory_to_project/venvPotato/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/username/directory_to_project/venvPotato/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/username/directory_to_project/venvPotato/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/username/directory_to_project/venvPotato/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/username/directory_to_project/venvPotato/lib/python3.10/site-packages/potato/flask_server.py", line 1167, in login
    return annotate_page(username)
  File "/home/username/directory_to_project/venvPotato/lib/python3.10/site-packages/potato/flask_server.py", line 2199, in annotate_page
    suggestions = instance['label_suggestions']
KeyError: 'label_suggestions'
```

**Workaround**
For the time being, installing a previous version solves this problem: 
```
pip uninstall potato-annotation

pip install potato-annotation==1.2.2.0
```

**Probable Cause**
Something in the newest commit [1.2.2.1 supports displaying label suggestions] 
→ https://github.com/davidjurgens/potato/commit/1986f5671d388856dd08f297c62c637f676ef160

**Comment by Jiaxin-Pei** [comment]
@christianschuler8989 thanks a lot for submitting this issue! This bug is fixed in [v1.2.2.2](https://github.com/davidjurgens/potato/commit/6ae6c4807d64486d3034a25dd5cc30195e978569), please upgrade to the latest version

**Comment by davidjurgens** [comment]
Fixed in Potato 2.0: The `label_suggestions` field is now accessed safely with `.get()` and existence checks before bracket access, preventing the KeyError crash. The entire annotation rendering pipeline has been rewritten.
