### ISSUE TITLE
Dynamic Highlighting

### ISSUE THREAD

**Issue by Naman-Bhrgv** [davidjurgens/potato#83]
Hi,
I am using Potato for my research, however, I haven't been ale to setup Dynamic Highlighting task. 

### Reproduction
I tried to include dynamic highlighting for dialogue_analysis task. Added `dynamic_key.tsv` file path to `dialogue-analysis.yaml` . Both `keyword.tsv` and `dialogue-analysis.yaml` files are present [here](https://drive.google.com/drive/folders/1o9GFHllZSNQprajEULT-QYfnVkFRUfLv?usp=sharing).

I have attached the snippet of annotation_schemes part of dialogue-analysis.yaml where I have added the path of dynamic_key.tsv file.

```
"annotation_schemes": [
        {
          "annotation_type": "highlight",
          "name": "certainty",
          "description": "Highlight which phrases make the sentence more or less certain",
          "labels": [
            "certain", "uncertain"
          ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
          "sequential_key_binding": True,
        },
        {
            "annotation_type": "radio",
            "name": "sentiment",
            "description": "What kind of sentiment does the given text hold?",
            "labels": [
               "positive", "neutral", "negative",
            ],

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Aannotations with more than 10 are not supported with this
            # simple keybinding and will need to use the full item specification
            # to bind all labels to keys.
            "sequential_key_binding": True,     
           "keyword_highlights_file":"dynamic_key.tsv"                      
        },
        
           
    ]
```

### Error Description

From what I understood from documentation, the keywords provided in tsv file will be highlighted automatically. However, even after adding the tsv file, the annotation task doesn't change. Can you tell me how to setup dynamic highlighting.
Thanks in advance!

**Comment by Jiaxin-Pei** [comment]
Hi @Naman-Bhrgv,

There are two issues in your current setup.
(1)  "keyword_highlights_file":"dynamic_key.tsv" should be added outside "annotation_schemes", for example:

```
"user_config": {
      "allow_all_users": True,
      "users": [  ],
    },

 "keyword_highlights_file": "dynamic_key.tsv",

```

(2) In the .tsv file, the column name should be `Label` instead of `labels`. 

Please fix these two issues and try again. 
You can also check our [this example project](https://github.com/davidjurgens/potato/tree/master/project-hub/immigration_framing) to see how dynamic highlight is configured.

**Comment by Naman-Bhrgv** [comment]
Thanks @Jiaxin-Pei it worked for me, btw I am also studying at University of Michigan and this tool has helped me a lot in my research.

**Comment by Naman-Bhrgv** [comment]
Hi @Jiaxin-Pei ,
Is there a way to edit the annotation for keywords specified in dynamic highlighting?

**Comment by davidjurgens** [comment]
What do you mean by "edit the annotation" here? Like to record which words
were highlighted at the time of annotation?

**Comment by Naman-Bhrgv** [comment]
No, I meant to edit the label pre-specified for words in the tsv file (which was input of dynamic highlighting).

**Comment by Jiaxin-Pei** [comment]
@Naman-Bhrgv Do you mean that you want to do span annotation for the dynamically highlighted words?

**Comment by Naman-Bhrgv** [comment]
Yes exactly

**Comment by Jiaxin-Pei** [comment]
@Naman-Bhrgv We don't currently support doing span annotations for the dynamically highlighted words. However, if you could describe your task in more detail, I can take a look and see if there are other ways to make it work! We do have some other relevant features that can potentially help!

**Comment by davidjurgens** [comment]
@Jiaxin-Pei I think it's possible to support those kinds of annotations
with some extensions to the tool though. It might be worth a look

**Comment by Jiaxin-Pei** [comment]
@davidjurgens Yes! I think we can either extend the [label suggestions](https://potato-annotation.readthedocs.io/en/latest/productivity/#label-suggestions) or the Dynamic highlighting to support this. Happy to take a look after @Naman-Bhrgv describes his exact use case.

**Comment by Naman-Bhrgv** [comment]
@Jiaxin-Pei I am following a two step approach for data annotation. These steps are-
1. We use spacy to label all the entities in text.
2. Then we load the text in potato and edit the entities labelled by spacy (incase they are incorrect) and label additional entities in the text.
Please provide some suggestions for it.

**Comment by Jiaxin-Pei** [comment]
Thanks a lot for sharing the details!
I think this is aligned with our development plan on [label suggestions](https://potato-annotation.readthedocs.io/en/latest/productivity/#label-suggestions). I can prioritize this feature and try to get this up early next week. Would this work for you? @Naman-Bhrgv

**Comment by Naman-Bhrgv** [comment]
Yeah that would be great. Thanks Jiaxin!

**Comment by isspek** [comment]
Hi @Jiaxin-Pei , @davidjurgens ,

I have actually a similar situation. I have long texts highlighted by GPT-4. I would like to ask annotators for editing the marked texts by GPT-4. The screenshot contains the highlighted text that I manually did by looking at the GPT-4 results. It is a bit time consuming and I got sometimes errors from potato when I did it manually. Here is an example of error:  

```shell
Traceback (most recent call last):
  File "/web/tmp/potato/venv/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/web/tmp/potato/venv/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/web/tmp/potato/venv/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/web/tmp/potato/venv/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "potato/flask_server.py", line 1189, in login
    return annotate_page(username)
  File "potato/flask_server.py", line 2216, in annotate_page
    text = render_span_annotations(text, span_annotations)
  File "/web/tmp/potato/potato/server_utils/schemas/span.py", line 109, in render_span_annotations
    bg_color = color.replace(")", ",0.25)")
AttributeError: 'NoneType' object has no attribute 'replace'
```

![Image](https://github.com/user-attachments/assets/55926087-ca29-4e2e-a196-2e18f455cd6c)

I assume that prefill is the method i need to take a look. But I couldn't find an example for this. Much appreciated if you can guard me on this case.

Thanks in advance.
