### ISSUE TITLE
Flask Server Exception

### ISSUE THREAD

**Issue by Naman-Bhrgv** [davidjurgens/potato#84]
Hi,

I was using Dialogue Analysis with dynamic highlight. I receive the following flask server error. Please note that this error is only coming after adding the dynamic highlighting tsv file.

# Reproduction

This is my modified config.yaml file. tsv file is added after the user_config. tsv file and modified dialogue_analysis task is attached [here](https://drive.google.com/drive/folders/1eOQYrD8-OXnObdK3lssuSp3_HMrqzJB7?usp=sharing).

```
{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Dialogue Analysis",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
       "data_files/dialogue-example.json"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "context"
    },


    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    "keyword_highlights_file": "dynamic_key.tsv",  

    #list_as_text is used when the input text is actually a list of texts, usually used for best-worst-scaling or dialogue analysis
    "list_as_text": {
      "text_list_prefix_type": 'none', #whether automatically insert a prefix for each line, currently supporting 'number', 'alphabet', 'number'
      "horizontal": True,
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [
        {
          "annotation_type": "highlight",
          "name": "certainty",
          "description": "Highlight which phrases make the sentence more or less certain",
          "labels": [
            "certain", "uncertain"
          ],

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
          "sequential_key_binding": True,
        },
        {
            "annotation_type": "radio",
            "name": "sentiment",
            "description": "What kind of sentiment does the given text hold?",
            "labels": [
               "positive", "neutral", "negative",
            ],

            # If true, numbers [1-len(labels)] will be bound to each
            # label. Aannotations with more than 10 are not supported with this
            # simple keybinding and will need to use the full item specification
            # to bind all labels to keys.
            "sequential_key_binding": True,                        
        },       
    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    # you may use templates in our lib, if you want to use your own template,
    # please replace the string as a path to the template
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default",

}
```  

Error-
```
ERROR:potato.flask_server:Exception on /annotate [POST]
Traceback (most recent call last):
  File "/home/naman/miniconda3/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naman/miniconda3/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naman/miniconda3/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naman/miniconda3/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naman/miniconda3/lib/python3.11/site-packages/potato/flask_server.py", line 2100, in annotate_page
    did_change = update_annotation_state(username, request.form)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naman/miniconda3/lib/python3.11/site-packages/potato/flask_server.py", line 1000, in update_annotation_state
    span_text, span_annotations = parse_html_span_annotation(span_annotation_html)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naman/miniconda3/lib/python3.11/site-packages/potato/flask_server.py", line 2460, in parse_html_span_annotation
    middle_text = middle[: m3.start()]
                           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by Jiaxin-Pei** [comment]
Thanks a lot for reaching out, @Naman-Bhrgv. I'm looking into it and please allow me a few days to diagnose the issue! I am also working on supporting preload span annotations and will keep you posted!
